SELECT strftime('%Y-%m', o.ORDER_DATE) AS YM,
       p.CATEGORY_CD,
       c.CATEGORY_NAME,
       COUNT(DISTINCT o.ORDER_ID) AS ORDER_CNT,
       SUM(i.QTY) AS QTY,
       SUM(i.AMOUNT) AS SALES_AMT
FROM TB_ORDER o
JOIN TB_ORDER_ITEM i ON o.ORDER_ID = i.ORDER_ID
JOIN TB_PRODUCT p ON i.PROD_ID = p.PROD_ID
JOIN TB_CATEGORY c ON p.CATEGORY_CD = c.CATEGORY_CD
WHERE o.STATUS NOT IN ('04', '05')
GROUP BY strftime('%Y-%m', o.ORDER_DATE), p.CATEGORY_CD, c.CATEGORY_NAME
